services:
  - type: web
    name: orcscanneer
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: MONGO_URI
        value: mongodb+srv://sree71816_db_user:NO5jq7RLo7dhcZHN@cluster0.gbttwr6.mongodb.net/business_card_db?retryWrites=true&w=majority
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app

